### ISSUE TITLE
Feature request: support for form-horizontal

### ISSUE THREAD

**Issue by vincentsels** [MacawNL/BootstrapEditorTemplates#1]
Nice initiative, but doesn't work with the form-horizontal option. Would be great if you could include that as an option somehow.

**Comment by Maarten88** [comment]
I'm sorry, it's too hard to include every variation someone might need. See these controls as a good starting point. It is easy to add variations yourself: just go into the EditorTemplates folder, copy the control that is closest to what you need and edit away.
