### ISSUE TITLE
Referenced assembly 'MarkdownDeep' does not have a strong name

### ISSUE THREAD

**Issue by richb81** [MacawNL/BootstrapEditorTemplates#2]
I am getting this error message after installing the package. Referenced assembly 'MarkdownDeep' does not have a strong name

**Comment by dingo99** [comment]
You could always build it from source and sign it yourself if you need a signed version, http://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0CB8QFjAA&url=http%3A%2F%2Fmsdn.microsoft.com%2Fen-us%2Flibrary%2Fxc31ft41%28v%3Dvs.110%29.aspx&ei=kG-xU9yDPdWksQT1l4HACQ&usg=AFQjCNHD7m-TZRj6QtXPz2LNEvvPTbl9XA&bvm=bv.69837884,d.cWc

**Comment by Maarten88** [comment]
Everytime you strong name an assembly, a kitten dies https://twitter.com/davidfowl/status/467418148451254272
