### ISSUE TITLE
EnumDropDownListFor in EditorTemplate is ambigius

### ISSUE THREAD

**Issue by NicoJuicy** [MacawNL/BootstrapEditorTemplates#5]
The call is ambiguous between the following methods or properties: 'Demo_Bootstrap.Utility.EnumDropDown.EnumDropDownListFor<object,object>(System.Web.Mvc.HtmlHelper<object>, System.Linq.Expressions.Expression<System.Func<object,object>>, object)' and 'System.Web.Mvc.Html.SelectExtensions.EnumDropDownListFor<object,object>(System.Web.Mvc.HtmlHelper<object>, System.Linq.Expressions.Expression<System.Func<object,object>>, object)' c:\Users\NSA-PC\Documents\Visual Studio 2013\Projects\Demo Bootstrap\Demo Bootstrap\Views\Shared\EditorTemplates\Enum.cshtml    7   6   Demo Bootstrap

Solution is to remove EnumDropDownList.cs for asp.net mvc 5.

**Comment by ThibaudAV** [comment]
I have the same problem :/

**Comment by Maarten88** [comment]
This happens after version 5.1 of ASP.NET MVC, which includes the exact same feature also using the same (obvious) name. The solution is to simply delete this class (/Utility/EnumDropDownList.cs) from the project, which I did in the new 1.2 version. Btw the Microsoft version is in System.Web.Mvc.Html.
