### ISSUE TITLE
Not working with Data Annotation [EmailAddress]

### ISSUE THREAD

**Issue by MestreMurai** [MacawNL/BootstrapEditorTemplates#6]
When a string field on model class is setted with an [EmailAddress] Data Annotation no Editor Template is loaded...same happens with annotation [DataType.EmailAddress].

**Comment by Maarten88** [comment]
The previous version does not have an email address template, so you would get the default one from MVC. For the new 1.2 version of the templates project I have added the EmailAddress template. It generates a bootstrap form group around a standard HTML5 input with type=email, including server and client side validation.
